### ISSUE TITLE
TypeScript error

### ISSUE THREAD

**Issue by RossComputerGuy** [voxpelli/pony-cause#35] opened 2022-05-15 01:35 UTC
```
node_modules/pony-cause/index.d.ts:5:5 - error TS2416: Property 'cause' in type 'ErrorWithCause<T>' is not assignable to the same property in base type 'Error'.
  Type 'T' is not assignable to type 'Error | undefined'.
    Type 'T' is not assignable to type 'Error'.

5     cause: T;
      ~~~~~


Found 1 error in node_modules/pony-cause/index.d.ts:
```

**Comment by floriankrueger** [comment] 2022-05-18 09:40
We're running into the same issue. Any plans to look into this?

**Comment by benasher44** [comment] 2022-05-18 13:45
Updating the constraint for the Error generic parameter for cause like this fixes it:

```typescript
ErrorWithCause<T extends Error | undefined = undefined>
```

**Comment by voxpelli** [comment] 2022-05-19 10:23
Relates to https://github.com/microsoft/TypeScript/issues/48098, and as @ljharb said in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59354#issuecomment-1073070185:

> the bug is in the base error cause types

And https://github.com/microsoft/TypeScript/issues/45167#issuecomment-1073077140 is still open for this very reason.

I note that there's also another incorrect `Error` related type in TS, that the type of `.stack` while being optional is not explicitly allowed to be `undefined`: https://github.com/microsoft/TypeScript/issues/45748

So: We have to fix this in TS.

In the meanwhile: You can downgrade to an older version of TS, like eg. TS 4.5, to avoid this error.

**Comment by voxpelli** [comment] 2022-05-19 10:23
Would by the way love a PR with a test case that reproduces this, so that we can more easily verify that its working again 👍

**Comment by voxpelli** [comment] 2022-05-19 17:33
Doing some more pinning down on when this was introduced:

1. This is caused by `"lib": ["es2022"]` or more specifically the `es2022.error` lib. `esnext` will include `es2022` on TS `4.6` and later.
2. No `es2022` stuff is documented in the [online `lib` documentation](https://www.typescriptlang.org/tsconfig#lib), but in the TS `4.6.4` CLI it is documented:
    > Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', **'es2022'**, 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'webworker.iterable', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2020.bigint', 'es2020.promise', 'es2020.sharedmemory', 'es2020.string', 'es2020.symbol.wellknown', 'es2020.intl', 'es2021.promise', 'es2021.string', 'es2021.weakref', 'es2021.intl', 'es2022.array', **'es2022.error'**, 'es2022.object', 'es2022.string', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint', 'esnext.string', 'esnext.promise', 'esnext.weakref'.
    The online `lib` documentation do state the very true:
    > This list may be out of date
3. `lib` will default to the value of `target`, so if `target` is `es2022` or `esnext` on TS `4.6` or later then it will include the troublesome new `Error` definition. And the [online `target` documentation](https://www.typescriptlang.org/tsconfig#target) does indeed document `es2022`

So, conclusion: You can also avoid this issue by setting `lib` implicitly through `target´ or explicitly to something that doesn't include `es2022.error`

**Comment by voxpelli** [comment] 2022-05-31 13:03
I have now merged #36 which added tests that reproduces this very fact.

**Comment by voxpelli** [comment] 2022-07-06 09:33
The mentioned PR has now been merged into TS: https://github.com/microsoft/TypeScript/pull/49639 

Not sure in what release it's going to appear. I hope it's going to be in at least TS 4.8

**Comment by voxpelli** [comment] 2022-07-20 02:13
#41 proves that current upcoming TS does indeed solve this issue.

**Closed** 2022-08-01 21:09 UTC
Labels: bug

**Comment by voxpelli** [comment] 2022-08-01 21:18
Published `2.1.0` that contains a fix for TS 4.6 and TS 4.7, as those two versions likely never will be fixed by TS

**Comment by SpencerKaiser** [comment] 2022-08-11 21:24
Thanks to everyone in the thread for the help! And an extra shoutout to @RossComputerGuy for the patch 🚀 

@voxpelli not sure if you're familiar with `umzug`, but [I started a discussion over there for them to add your patch ](https://github.com/sequelize/umzug/discussions/561) 🙂

**Comment by voxpelli** [comment] 2022-08-11 21:27
@SpencerKaiser Thanks for bringing it to mine and their attention 🙏 I replied in that thread asking if they would want me to backport the fix to `1.x`

**Comment by voxpelli** [comment] 2022-08-26 12:42
TS 4.8 is now released. If you update to that one then everything will work as it should thanks to the corrected `lib.d.ts`: https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#lib-d-ts-updates
